# -*- coding: utf-8 -*-
"""判斷偶數

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18fV_Q8guEu5UEjG86S_wMKMGwX6T5VY2
"""

def main():
    try:
        # 讓使用者輸入一個整數
        user_input = input("請輸入一個整數：")

        # 檢查是否輸入了空字符串
        if user_input.strip() == "":
            print("請勿輸入空字符串。")
            return

        # 將輸入轉換為整數
        number = int(user_input)

        # 判斷是否為偶數
        if number % 2 == 0:
            print(f"{number} 是偶數。")
        else:
            print(f"{number} 不是偶數。")

    except ValueError:
        print("請輸入一個有效的整數。")

if __name__ == "__main__":
    main()