# -*- coding: utf-8 -*-
"""收集用戶資料

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sKkoRfGQ92yD1fGXuucib8s5okjaFNMW
"""

def main():
    # 收集用戶資料
    name = input("請輸入您的姓名：")
    age = int(input("請輸入您的年齡："))
    height = float(input("請輸入您的身高（米）："))
    favorite_color = input("請輸入您喜愛的顏色：")

    # 建立用戶資料字典
    user_data = {
        "姓名": name,
        "年齡": age,
        "身高": height,
        "喜愛的顏色": favorite_color
    }

    # 輸出格式化的個人資料摘要
    print(f"{user_data['姓名']}, {user_data['年齡']}歲, 身高{user_data['身高']}米, 喜愛的顏色是{user_data['喜愛的顏色']}。")

if __name__ == "__main__":
    main()